MVC C#_ en visualBasic venta de excursiones/Obligatorio2Programacion2/Controllers/CompraController.cs
using obligatorioProgramacion2;
using Obligatorio2Programacion2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Obligatorio2Programacion2.Controllers
{
    public class CompraController : Controller
    {
        Agencia a = Agencia.GetInstancia();
        // GET: Compra
        public ActionResult Index()
        {
            if ((string)Session["logueadoRol"] == null)
            {
                ViewBag.MSG = "Para Ver sus compras inicie sesion";
                return View("../Home/Index");
            }
            // numero de cedula del usuario que es igual a su nombre de usuario 
            else
            {
                int Usuario = (int)Session["logueadoUsuario"];

                return View(a.GetComprasPorCliente(Usuario));
            }
        }

        //Metodo para cancelar compra 
        public ActionResult Cancelar(int id)
        {
            if ((string)Session["logeadoRol"] == "Cliente")
            {
                Compra c = a.GetComprasPorId(id);
                a.cancelarCompra(c.Id);

                ViewBag.Msg = "Compra Cancelada con exito";
                return View("../Home/Index");
            }
            else {
                ViewBag.Msg = "Usted no puede acceder a esta parte del sitio, para Acceder inicie sesion";
                return View("../Home/Index");
            }


        }

        //Get Compra Entre Dos Fechas
        public ActionResult ComprasEntreDosFechas()
        {
            
            if ((string)Session["logueadoRol"] == "Operador")
            {

                return View("ComprasEntreDosFechas");
            }
            else {
                ViewBag.Msg = "Usted no tiene autorizacion para ingresar a este sitio, ingrese como Operador";
                return View("../Home/Index");
            }

        }


        // Metodo para ver las compras entre dos fechas
        [HttpPost]
        public ActionResult ComprasEntreDosFechas(DateTime? FechaInicial, DateTime? FechaFinal)
        {

            DateTime FechaI;
            DateTime FechaF;
            double totalPesos = 0;
            double totalDolares = 0;

            if (FechaInicial != null)
            {
                FechaI = FechaInicial.Value;

            }
            else
            {
                FechaI = DateTime.Today;
            }
            if (FechaFinal != null)
            {
                FechaF = FechaFinal.Value;
            }
            else
            {
                FechaF = DateTime.Today;
            }

            foreach (Compra C in a.GetCEntreFechas(FechaI, FechaF))
            {

                totalPesos = C.costoTotalPesos + totalPesos;
                totalDolares = totalDolares + C.costoTotalDolares;


            }
            ViewBag.Pesos = totalPesos;
            ViewBag.Dolares = totalDolares;
            if (a.GetCEntreFechas(FechaI, FechaF).Count() == 0) {
                ViewBag.comprasFecha = "No hay compras entre esas dos fechas";
            }


            return View(a.GetCEntreFechas(FechaI, FechaF));
        }

    }
}

MVC C#_ en visualBasic venta de excursiones/Obligatorio2Programacion2/Controllers/UsuarioController.cs
using Obligatorio2Programacion2.Models;
using obligatorioProgramacion2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Obligatorio2Programacion2.Controllers
{
    public class UsuarioController : Controller
    {
        Agencia a = Agencia.GetInstancia();
        // GET: Usuario
        public ActionResult Index()
        {
            if ((string)Session["logueadoRol"] == "Operador")
            {
                if (a.GetClientes().Count() == 0) {
                    ViewBag.noHayC = "No hay clientes";
                }

                return View(a.GetClientes());
            }
            else {
                ViewBag.Msg = "Ingrese como Operador Para Acceder a esta funcion";
                return View("../Home/Index");
            }

        }
        public ActionResult Registrarse()
        {
            return View();
        }

        // POST: Usuario/Registrarse
        [HttpPost]
        public ActionResult Registrarse(Usuario u)
        {

            try
            {
                Usuario Usu =  a.agregarCliente(u.Nombre, u.Apellido, u.Cedula, u.Password);
                a.agregarCliente(u.Nombre, u.Apellido, u.Cedula, u.Password);
                if (Usu != null)
                {
                    

                    ViewBag.Msg = "Bienvenido " + Usu.Nombre + " " + Usu.Apellido + " Inicie sesion para continuar";

                }
                else {
                    ViewBag.Msg = "No se pudo Registrar su usuario, verifique sus datos";
                }
                
                return View("../Home/Index");
                
            }
            catch
            {
                return View();
            }
        }

    }
}

MVC C#_ en visualBasic venta de excursiones/Obligatorio2Programacion2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if ((string)Session["logueadoRol"] == "Operador")
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Agencia de viajes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Log Out", "LogOut", "Home")</li>
                        <li>@Html.ActionLink("Vizualizar compras entre dos fechas", "ComprasEntreDosFechas", "Compra")</li>
                        <li>@Html.ActionLink("Visualizar clientes", "Index", "Usuario")</li>
                        <li>@Html.ActionLink("Estadisticas", "Estadisticas", "Excursion")</li>
                    </ul>
                </div>
            </div>
        </div>
        

    }
    @if ((string)Session["logueadoRol"] == "Cliente")
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Agencia de viajes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Log Out", "LogOut", "Home")</li>
                        <li>@Html.ActionLink("Vizualizar excursiones", "Index", "Excursion")</li>
                        <li>@Html.ActionLink("Compras", "Index", "Compra")</li>
                    </ul>
                </div>
            </div>
        </div>


    }
    @if ((string)Session["logueadoRol"] == null)
    {
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Agencia de viajes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log In", "Login", "Home")</li>
                    <li>@Html.ActionLink("Ver Excursiones", "Index", "Excursion")</li>
                    <li>@Html.ActionLink("Registrarse", "Registrarse", "Usuario")</li>
                  
                </ul>
            </div>
        </div>
    </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>