MVC C# venta Vacunas con MYSQL_ y APIrest/Obli/MVC/Controllers/ConsumidorApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using Dominio.EntidadesNegocio;
using MVC.Models;
using System.Net;


namespace MVC.Controllers
{
    public class ConsumidorApiController : Controller
    {
        HttpClient cliente = new HttpClient();
        HttpResponseMessage response = new HttpResponseMessage();
        Uri productoUri = null;

        public ConsumidorApiController()
        {
            cliente.BaseAddress = new Uri("http://localhost:64769/");
            productoUri = new Uri("http://localhost:64769/api/VacunasApi");
            cliente.DefaultRequestHeaders.Accept.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
        }

        public ActionResult FindAll()
        {
            response = cliente.GetAsync(productoUri + "/TodasLasVacunas").Result;
            if (response.IsSuccessStatusCode)
            {
                var vacunas = response.Content.ReadAsAsync<IEnumerable<ModeloVacEntero>>().Result;
                return View(vacunas);
            }
            else
            {
                ViewBag.ResultadoOperacion = "No hay vacunas";
                return View("Errorusuario", "Home");
            }
        }

        public ActionResult Detalles(string NombreVacuna)
        {
            
            response = cliente.GetAsync(productoUri +  "/BuscarPorId?NombreVacuna=" + NombreVacuna).Result;
            
           

            if (response.IsSuccessStatusCode)
            {
                var VacunaBuscada = response.Content.ReadAsAsync<ModeloVacEntero>().Result;
                response = cliente.GetAsync(productoUri + "/TodosLosPrestadores" ).Result;
                var prestador = response.Content.ReadAsAsync<IEnumerable<ModeloIpss>>().Result;
                ViewBag.prestadores = prestador;

                return View(VacunaBuscada);
            }
            else
            {
                // hay que "resolver" el tema del viewbag en la lista segun como organizemos la misma 
                ViewBag.ResultadoOperacion = "No se encontro la vacuna: " + NombreVacuna;
                return View("Errorusuario", "Home");
            }



        }
        public ActionResult VacunasMuchosCriterios()
        {
            return View("VacunasMuchosCriterios");
        }

        [HttpPost]
        public ActionResult VacunasMuchosCriterios(int? faseAprobacion, decimal? topeMax, decimal? topeMin, int? idTipoVac, string laboratorio, string pais, bool? todos)
        {
            if (todos == null)
            {
                todos = false;
            }
            response = cliente.GetAsync(productoUri +
                "/BuscarMuchosCriterios?faseAprobacion="+faseAprobacion
                +"&topeMax="+ topeMax
                +"&topeMin="+ topeMin
                +"&idTipoVac="+ idTipoVac
                +"&laboratorio=" + laboratorio
                +"&pais="+pais
                +"&todos="+todos
                ).Result;
            if (response.IsSuccessStatusCode)
            {
                var vacunas = response.Content.ReadAsAsync<IEnumerable<ModeloVacEntero>>().Result;
                return View(vacunas);
            }
            else
            {
                ViewBag.ResultadoOperacion = "No hay vacunas";
                return View("Errorusuario", "Home");
            }
        }

        public ActionResult FindAllIpss()
        {
            response = cliente.GetAsync(productoUri + "/TodosLosPrestadores").Result;
            if (response.IsSuccessStatusCode)
            {
                var prestadores = response.Content.ReadAsAsync<IEnumerable<ModeloIpss>>().Result;
                return View(prestadores);
            }
            else
            {
                ViewBag.ResultadoOperacion = "No hay ninguna institucion prestadora de salud ";
                return View("Errorusuario", "Home");
            }
        }

        public ActionResult FindById(int? id)
        {
            response = cliente.GetAsync(productoUri + "/IpssXId?id="+id).Result;
            if (response.IsSuccessStatusCode)
            {
                var vacunas = response.Content.ReadAsAsync<ModeloIpss>().Result;
                return View(vacunas);
            }
            else
            {
                ViewBag.ResultadoOperacion = "No hay ninguna institucion prestadora de salud ";
                return View("Errorusuario", "Home");
            }
        }
        public ActionResult FindByComprador(int id)
        {
            response = cliente.GetAsync(productoUri + "/CompraXcomprador?id=" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                var compras = response.Content.ReadAsAsync<IEnumerable<ModeloCompras>>().Result;
                int contadorCompras = 0;
                
                decimal comprasDelMes = 0;
                foreach (ModeloCompras c in compras) {
                    if (c.FechaCompra.Month == DateTime.Today.Month) {
                        contadorCompras++;
                        comprasDelMes = comprasDelMes + c.TotalCompra;
                        
                    }
                }
                response = cliente.GetAsync(productoUri + "/IpssXId?id=" + id).Result;
                var comprador = response.Content.ReadAsAsync<ModeloIpss>().Result;
                decimal Saldo = comprador.GastoMaxXAfiliado * comprador.CantAfiliados;

                ViewBag.CompraRes = comprador.CantidadMaxComprasMensuales - contadorCompras;
                ViewBag.DineroAuto = Saldo;
                ViewBag.Saldo = Saldo - comprasDelMes;

                return View(compras);
            }
            else
            {
                ViewBag.ResultadoOperacion = "No hay ninguna institucion prestadora de salud ";
                return View("Errorusuario", "Home");
            }
        }

        // Compra
        [HttpPost]
        
        public ActionResult Comprar(string Nombre, decimal Precio,int Cantidad,int opciones )
        {
            Models.ModeloCompras com = new ModeloCompras {
              NombreVacuna = Nombre,
              PrecioUnitVacuna=Precio,
              CantDosisCompradas=Cantidad,
              NroCompradorMSP=opciones,
              TotalCompra=Precio*Cantidad,
              FechaCompra= DateTime.Today,
            };
            if (com!=null)
            {

                //cliente.BaseAddress = productoUri;

                var tareaPost = cliente.PostAsJsonAsync(productoUri, com);

                var result = tareaPost.Result;

                if (result.IsSuccessStatusCode)
                {
                    TempData["ResultadoOperacion"] = "Agregado el producto ";

                    return RedirectToAction("FindByComprador", new { id = opciones });
                }
                return View("Errorusuario","Home");
            }
            else
            {
                TempData["ResultadoOperacion"] = "Ups! Verifique los datos";

                return RedirectToAction("Index","Home");
            }
        }
        




      
    }
}

MVC C# venta Vacunas con MYSQL_ y APIrest/Obli/MVC/Controllers/IpssController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dominio.EntidadesNegocio;
using Repositorios;

namespace MVC.Controllers
{
    public class IpssController : Controller
    {
        RepositorioIpss repoIpss = new RepositorioIpss();
       
        public ActionResult AgregarIpss()
        {
            return View("AgregarIpss");
        }

        [HttpPost]
        public ActionResult AgregarIpss(Models.ModeloIpss unIpss)
        {
            Ipss unaInst = new Ipss
            {
                NroMSP = unIpss.NroMSP,
                Nombre = unIpss.Nombre,
                CantidadMaxComprasMensuales = unIpss.CantidadMaxComprasMensuales,
                CantAfiliados = unIpss.CantAfiliados,
                GastoMaxXAfiliado = unIpss.GastoMaxXAfiliado,
                Telefono = unIpss.Telefono,
                NombreContacto = unIpss.NombreContacto,

            };
            if (unIpss != null) {
                repoIpss.Add(unaInst);


            }





            return View("../Home/Index");
        }
    }
}

MVC C# venta Vacunas con MYSQL_ y APIrest/Obli/MVC/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Dominio.EntidadesNegocio;
using Repositorios;

namespace MVC.Controllers
{
    public class UsuarioController : Controller
    {
        RepositorioUsuario repoUsu = new RepositorioUsuario();
        public ActionResult LogIn()
        {
            return View("LogIn");

        }
        [HttpPost]
        public ActionResult LogIn(Models.LogIn logIn)
        {
            Usuario unUsu = repoUsu.FindByCedula(logIn.Cedula);
            string pass = unUsu.Password;
            string encriptada = Encriptar.GetSHA256(logIn.Password);
            if (pass == encriptada)
            {  Session["Cedula"] = logIn.Cedula;
                if (unUsu.PrimeraVes)
                {
                   
                    return View("ConfirmaPassword");
                }
                else
                {
                    return View("../Home/Index");
                }

            }
            return View("../Home/Index");

        }
        public ActionResult ConfirmaPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ConfirmaPassword(Models.ModeloPassword pass)
        {
            
            string cedula = (string)Session["Cedula"];
            Usuario unUsu = repoUsu.FindByCedula(cedula);
            string encriptada = Encriptar.GetSHA256(pass.Pass1);
            Usuario usu = new Usuario
            {
                Cedula = cedula,
                Password = pass.Pass1,
                PrimeraVes = false,
                
            };
            bool ok = repoUsu.Update(usu);
            if (ok)
            {
                return View("../Home/Index");
            }
            else {
                Session["Cedula"] = "";
                    return View("../Home/Index");
            }
                
        }

        public ActionResult LogOut()
        {
            Session["Cedula"] = null;
            return View("LogIn");

        }



    }
}

MVC C# venta Vacunas con MYSQL_ y APIrest/Obli/MVC/Views/Shared/_Layout.cshtml
@if (Session["Cedula"] != null)
{




    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
        <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Carga de Archivos", "volcadoArchivos", "Home")</li>
                        <li>@Html.ActionLink("Agreagar Ipss", "AgregarIpss", "Ipss")</li>
                        <li>@Html.ActionLink("Buscar Vacunas", "VacunasMuchosCriterios", "ConsumidorApi")</li>
                        <li>@Html.ActionLink("Log out", "LogOut", "Usuario")</li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

}
else
{


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Carga de Archivos", "volcadoArchivos", "Home")</li>
                    <li>@Html.ActionLink("Log in", "LogIn", "Usuario")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>






}